export enum MenuItems {
  MUSIC = 'MUSIC',
  ARTISTS = 'ARTISTS',
  ABOUT = 'ABOUT',
  NEWS = 'NEWS',
  EVENTS = 'EVENTS',
  PROGRAMMING = 'PROGRAMMING',
  GOLD = 'GOLD',
  PARTNERS = 'PARTNERS',
  PRESS = 'PRESS',
  PLAYER = 'PLAYER',
  SHOP = 'SHOP',
  LOST_CIVILIZATION = 'LOST CIVILIZATION',
}
